### PR TITLE
Swap out or remove Deprecated packages

### PR DESCRIPTION
**Pull request by Jozzey**
https://github.com/DEFRA/water-abstraction-team/issues/22

We are finding as we go through the code base that we have a number of deprecated packages.

They are no longer maintained so we need to get them out. If we don't, we expose ourselves to unfixed errors, vulnerabilities, and issues when we come to upgrade other packages.

### CODE REVIEW

**Comment by Jozzey** [comment]
Dependency `file-type` is now ESM only. I tried updating to the latest version pre ESM only (v16.5.3) but it still breaks so will leave this one for another PR.

**Comment by Jozzey** [comment]
Could not easily bump `got` to version 12 as it is now ESM only so have just bumped the patch version.

**Comment by Jozzey** [comment]
Skipping a major version bump of `govuk-frontend` as I'm not sure what impact it will have on the appearance of the app without spending some time investigating.

**Comment by Jozzey** [comment]
Not updated `iframe-resizer` as the latest version only supports back to IE11 whereas V3 supports back to IE8. Thought I'd play it safe as I'm not sure what issues this may cause.

**Comment by Jozzey** [comment]
Only bumped 1 major version of `parse-domain` as from V6 onwards it is ESM only.

**Comment by Jozzey** [comment]
Not bumped `read-chunk` as V4+ is ESM only

**Comment by Jozzey** [comment]
Not bumped `del` as V7 is ESM only.

**Comment by Jozzey** [comment]
`hapi-auth-cookie` is depreciated and superseded by `@hapi/cookie`. May be a bit of work to get that updated so will do in a separate PR.

**Comment by Jozzey** [comment]
`hapi-auth-cookie` is depreciated and is now available at `@hapi/cookie`. Going to be a bit of work to get this one updated so will do in a separate PR.

**Comment by Jozzey** [comment]
Not updating `@hapi/catbox-redis` in this PR as it needs a bit of work to get working so will do in a separate PR.

**Comment by Jozzey** [comment]
I've just done the packages that didn't require too much effort to update. The remaining ones I'll pick up in their own separate PRs

**Review by Cruikshanks — APPROVED** [review]

**Pull request merged**
